// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAto7fMfiByDm8JpHnbin4m8t4bEiGKozQ',
    appId: '1:145407309827:android:1dc2e35fd4d9e3b92ef636',
    messagingSenderId: '145407309827',
    projectId: 'xafe-21334',
    storageBucket: 'xafe-21334.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx-66RQ--WlzNeMePrWjJRSLtCN6Fj8Bk',
    appId: '1:145407309827:ios:5959658cd52083332ef636',
    messagingSenderId: '145407309827',
    projectId: 'xafe-21334',
    storageBucket: 'xafe-21334.appspot.com',
    androidClientId: '145407309827-8p8hhggedtne5vl6dtcfr4ci5o6euld5.apps.googleusercontent.com',
    iosClientId: '145407309827-iuhrparpcvqlp9qq96gngpq093mtk4es.apps.googleusercontent.com',
    iosBundleId: 'com.example.xafe.xafe',
  );
}
